site_name: Zipline
repo_url: https://github.com/quantopian/zipline
site_author: Quantopian Inc.

pages:
- ['index.md', 'Overview']
- ['tutorial.md', 'Tutorial', 'Getting started']
- ['release-notes/zipline-0.8.0.md', 'Release notes']
- ['release-notes/zipline-0.7.0.md', 'Release notes']
- ['release-notes/zipline-0.6.1.md', 'Release notes']
